# Ore Miners Config File
#-----------------------------------------------------#

# Machine Spawning
machine:
  # Command from https://mrgarretto.com/armorstand/
  # Must be generated as "Single" and only use "Medium" or "Large" pieces. That means NO part can be "Small" or "Solid" otherwise it will break the plugin.
  # Special items:
  #  - Hopper: Drill piece, will rotate in-game & display break particles
  #  - Redstone Torch: Indicator light
  #  - Dispenser: Engine, will produce smoke
  #
  spawn_command: 'summon falling_block ~ ~1.0 ~ {Block:stone,Time:1,Passengers:[{id:falling_block,Block:redstone_block,Time:1,Passengers:[{id:falling_block,Block:activator_rail,Time:1,Passengers:[{id:commandblock_minecart,Command:"gamerule commandBlockOutput false"},{id:commandblock_minecart,Command:"summon armor_stand ~-0.84375 ~-3.55168 ~0.182804 {Pose:{Head:[-60f,0f,0f]},Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:end_rod}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~-0.84375 ~-4.06105 ~0.222656 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:hopper}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~-0.84375 ~-3.14543 ~0.182804 {Pose:{Head:[-60f,0f,0f]},Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:end_rod}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~-1.112904 ~-3.62466 ~0.304688 {Pose:{Head:[0f,0f,70f]},DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:stick}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.09375 ~-4.37883 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:1}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.09375 ~-3.34758 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:1}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.09375 ~-3.97258 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:1}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.71875 ~-4.37883 ~0.65625 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:7}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.09375 ~-2.07668 ~0.03125 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:1}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.125 ~-2.91008 ~0.367188 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:redstone_torch}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~-0.945733 ~-3.57456 ~0.492188 {Pose:{Head:[0f,0f,45f]},DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:stick}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.71875 ~-4.37883 ~-0.5625 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:7}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.71875 ~-4.37883 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:7}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~-0.84375 ~-2.67043 ~0.03125 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:redstone_block}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~1.34375 ~-4.37883 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:7}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~1.34375 ~-4.37883 ~-0.5625 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:7}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~1.34375 ~-4.37883 ~0.65625 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:7}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.8125 ~-3.26418 ~-0.5 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:4}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.8125 ~-3.26418 ~0.5625 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:4}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.942196 ~-3.11418 ~0.03125 {Pose:{Head:[0f,0f,60f]},Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:dispenser}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~1.25 ~-3.35793 ~0.5625 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:4}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~1.25 ~-3.35793 ~-0.5 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:wool,Damage:4}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.4375 ~-4.19133 ~0.5234380000000001 {Pose:{Head:[0f,0f,-90f]},DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:torch}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.4375 ~-4.19133 ~0.08593800000000001 {Pose:{Head:[0f,0f,-90f]},DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:torch}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.71875 ~-3.75383 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:mob_spawner}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.71875 ~-2.92043 ~0.03125 {Small:1,DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:diamond_block}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~0.71875 ~-3.97258 ~0.03125 {DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:dragon_egg}]}"},{id:commandblock_minecart,Command:"summon armor_stand ~-0.945733 ~-3.58831 ~0.11718800000000001 {Pose:{Head:[0f,0f,45f]},DisabledSlots:4096,Invisible:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:stick}]}"},{id:commandblock_minecart,Command:"setblock ~ ~ ~1.0 command_block 0 replace {Command:\"fill ~ ~-3 ~-1 ~ ~ ~ air\"}"},{id:commandblock_minecart,Command:"setblock ~ ~-1 ~1.0 redstone_block"},{id:commandblock_minecart,Command:"kill @e[type=commandblock_minecart,r=1]"}]}]}]}'

  # Location the machine faces when spawned using the command
  # Possible Values: 'NORTH', 'EAST', 'SOUTH', 'WEST'
  facing: WEST

  # How close a player must be until the machine spawns in the armour stands
  # Distance is in blocks
  render_distance: 45

  # How close a player must be before the machine makes noise and animates.
  # Distance is in blocks
  animation_distance: 15

  # How large the area of same material must be until it is considered a
  # resource node. This means a miner can be placed on it.
  # Resource nodes and configuration is defined in production
  node_area:
    x: 5
    z: 5

  # The recipe used to craft a machine
  # Must be a full 3x3 grid of items
  # Amount = amount of machines created
  crafting_recipe:
    1: AIR,IRON_BLOCK,REDSTONE_BLOCK
    2: BEACON,IRON_BLOCK,END_ROD
    3: IRON_BLOCK,IRON_BLOCK,HOPPER
    amount: 3

# Resource Production
# Format: 
#   ingame_item:                 <- The Material name of the resource node
#     production_per_min: amount <- Amount of items the machine produces per min
#     fuel_per_min: 30           <- The amount of fuel (coal) this machine uses per min
#     produces: item             <- The Material name of the item the machine produces
#
# Removing / adding productions here will define what are the resource nodes
#
production:
  grass_block:
    production_per_min: 60
    fuel_per_min: 30
    produces: dirt

  cobblestone:
    production_per_min: 120
    fuel_per_min: 10
    produces: cobblestone

  obsidian:
    production_per_min: 2
    fuel_per_min: 15
    produces: obsidian

  coal_ore:
    production_per_min: 200
    fuel_per_min: 20
    produces: coal

  iron_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: iron_ingot

  redstone_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: redstone

  lapis_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: lapis_lazuli

  nether_quartz_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: quartz

  gold_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: gold_ingot

  emerald_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: emerald

  diamond_ore:
    production_per_min: 60
    fuel_per_min: 30
    produces: diamond

# Async Update Settings
async_update:
  # The server ticks between each async machine update
  # This handles:
  #   - The loading / unloading of armor_stands, depending on player locations
  #   - Updating the amount of items the machine has produced, and fuel burnt
  #
  # The lower the value, the more responsive the machines. i.e. The quicker machine renders,
  # produced items are visible. Does not affect production rates, just when items become accessible.
  # 
  machine_tick_speed: 20

  # The server ticks between each async machine animation
  # The lower the value, the smoother the animation.
  machine_animate_speed: 2
